app1/urls.py
from django.urls import path, include
from . import views

app_name = 'app1'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('nuevaRuta', views.nuevo, name='nuevo'),
    path('welcome', views.welcome, name='welcome'),
]

app3/urls.py
from django.urls import path, include
from . import views

app_name = 'app3'

urlpatterns = [
    path('', views.directorio, name='directorio'),
    path('nuevoRegistro',views.nuevoRegistro,name='nuevoRegistro'),
    path('nuevoDepartamento',views.nuevoDepartamento,name='nuevoDepartamento'),
    path('vistaDepartamento/<str:idDepartamento>',views.vistaDepartamento,name='vistaDepartamento'),
    path('vistaUsuario/<str:idPersona>',views.vistaUsuario,name='vistaUsuario')
]

miPrimerProyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1',include('app1.urls')),
    path('app2',include('app2.urls')),
    path('app3/',include('app3.urls')),
    path('',include('app4.urls'))
]

#DIRECCION BASE : 127.0.0.1:8000 / app2 /

app3/models.py
from django.db import models

# Create your models here.

class departamento(models.Model):
    nombreDepartamento = models.CharField(max_length=48, null=True, blank=True)
    descripcionDepartamento = models.CharField(max_length=256, null=True, blank=True)


class persona(models.Model):
    nombre = models.CharField(max_length=32, null=True, blank=True)
    apellido = models.CharField(max_length=32, null=True, blank=True)
    numero = models.CharField(max_length=24, null=True, blank=True)
    email = models.CharField(max_length=48, null=True, blank=True)
    descripcion = models.CharField(max_length=256, null=True, blank=True)
    depaRelacionado = models.ForeignKey(departamento, null=True, blank=True, on_delete=models.SET_NULL)

app3/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import departamento, persona

# Create your views here.
def directorio(request):
    listaDepartamentos = departamento.objects.all().order_by('id')
    listaPersonas = persona.objects.all()
    return render(request,'directorio.html',{
        'listaDepartamentos':listaDepartamentos,
        'listaPersonas':listaPersonas
    })

def nuevoRegistro(request):
    listaDepartamentos = departamento.objects.all().order_by('id')
    if request.method == 'POST':
        nombreRegistro = request.POST.get('nombreRegistro')
        apellidoRegistro = request.POST.get('apellidoRegistro')
        numeroRegistro = request.POST.get('numeroRegistro')
        emailRegistro = request.POST.get('emailRegistro')
        descripcionRegistro = request.POST.get('descripcionRegistro')
        depaRegistro = request.POST.get('departamentoSeleccionado')
        print(depaRegistro)
        depaRelacionado = departamento.objects.get(id=depaRegistro)
        objPersona = persona.objects.create(
            nombre=nombreRegistro,
            apellido=apellidoRegistro,
            numero=numeroRegistro,
            email=emailRegistro,
            descripcion=descripcionRegistro,
            depaRelacionado=depaRelacionado
        )
        objPersona.save()
        return HttpResponseRedirect(reverse('app3:directorio'))
    return render(request,'nuevoRegistro.html',{
        'listaDepartamentos':listaDepartamentos
    })

def nuevoDepartamento(request):
    listaDepartamentos = departamento.objects.all().order_by('id')
    if request.method == 'POST':
        nombreDepartamento = request.POST.get('nombreDepartamento')
        descripcionDepartamento = request.POST.get('descripcionDepartamento')
        objDepartamento = departamento.objects.create(
            nombreDepartamento=nombreDepartamento,
            descripcionDepartamento=descripcionDepartamento
        )
        objDepartamento.save()
        return HttpResponseRedirect(reverse('app3:directorio'))
    return render(request,'nuevoDepartamento.html',{
        'listaDepartamentos':listaDepartamentos
    })

def vistaDepartamento(request,idDepartamento):
    listaDepartamentos = departamento.objects.all().order_by('id')
    objDeparamento = departamento.objects.get(id=idDepartamento)
    listaUsuarios = objDeparamento.persona_set.all()
    return render(request,'vistaDepartamento.html',{
        'listaDepartamentos':listaDepartamentos,
        'objDepartamento':objDeparamento,
        'listaUsuarios': listaUsuarios
    })

def vistaUsuario(request,idPersona):
    listaDepartamentos = departamento.objects.all().order_by('id')
    objPersona = persona.objects.get(id=idPersona)
    return render(request,'vistaUsuario.html',{
        'listaDepartamentos':listaDepartamentos,
        'objPersona':objPersona,
    })

app3/templates/directorio.html
{% extends "layout.html" %}

{% block title %}
    Directorio
{% endblock %}

{% block contenido %}
    {% for personaInfo in listaPersonas %}
    <div>
        <a href="{% url 'app3:vistaUsuario' personaInfo.id %}">{{ personaInfo.nombre }} {{ personaInfo.apellido }}</a>
    </div>
    {% endfor %}
{% endblock %}

app3/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>

        <!--INCLUSION DE BOOTSTRAP-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-2" >
                <h2>Directorio</h2>
                <form>
                    <input type="text" class="form-control">
                    <input type="submit" class="btn btn-success" value="Buscar">
                </form>
                <div>
                    <a href="{% url 'app3:directorio' %}">Home</a>
                </div>
                <br>
                <div>
                    <a href="{% url 'app3:nuevoRegistro' %}">Crear nuevo registro</a>
                </div>
                <div>
                    <a href="{% url 'app3:nuevoDepartamento' %}">Crear nuevo departamento</a>
                </div>
                <br>
                {% for departamentoInfo in listaDepartamentos %}
                <div>
                    <a href="{% url 'app3:vistaDepartamento' departamentoInfo.id %}">{{ departamentoInfo.nombreDepartamento }}</a>
                </div>
                {% endfor %}
            </div>
            <div class="col-lg-10">
                {% block contenido %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

app3/templates/nuevoDepartamento.html
{% extends "layout.html" %}

{% block title %}
    Nuevo departamento
{% endblock %}


{% block contenido %}
    <h2>Crear nuevo departamento</h2>
    <form class="row" method="post" action="{% url 'app3:nuevoDepartamento' %}">
        {% csrf_token %}
        <div>
            <label>Ingresar nombre</label>
            <input type="text" name="nombreDepartamento">
        </div>
        <div>
            <label>Ingresar descripcion</label>
            <input type="text" name="descripcionDepartamento">
        </div>
        <div>
            <input type="submit" value="Registrar">
        </div>
    </form>
{% endblock %}

app3/templates/nuevoRegistro.html
{% extends "layout.html" %}

{% block title %}
    Nuevo registro
{% endblock %}


{% block contenido %}
    <h2>Crear nuevo registro</h2>
    <form class="row" method="post" action="{% url 'app3:nuevoRegistro' %}">
        {% csrf_token %}
        <div>
            <label>Ingresar nombre</label>
            <input type="text" name="nombreRegistro">
        </div>
        <div>
            <label>Ingresar apellido</label>
            <input type="text" name="apellidoRegistro">
        </div>
        <div>
            <label>Ingresar numero</label>
            <input type="text" name="numeroRegistro">
        </div>
        <div>
            <label>Ingresar email</label>
            <input type="text" name="emailRegistro">
        </div>
        <div>
            <label>Ingresar descripcion</label>
            <input type="text" name="descripcionRegistro">
        </div>
        <div>
            <label>Seleccionar departamento</label>
            <select name="departamentoSeleccionado" required>
                <option value="" selected></option>
                {% for depaInfo in listaDepartamentos %}
                <option value="{{ depaInfo.id }}">{{ depaInfo.nombreDepartamento }}</option>
                {% endfor %}
            </select>
        </div>
        <div>
            <input type="submit" value="Registrar">
        </div>
    </form>
{% endblock %}

app3/templates/vistaDepartamento.html
{% extends "layout.html" %}

{% block title %}
    {{ objDepartamento.nombreDepartamento }}
{% endblock %}

{% block contenido %}
    <h1>{{ objDepartamento.nombreDepartamento }}</h1>
    <div>
        <h4>{{ objDepartamento.descripcionDepartamento }}</h4>
    </div>
    <br>
    {% for personaInfo in listaUsuarios %}
    <div>
        <a href="{% url 'app3:vistaUsuario' personaInfo.id %}">{{ personaInfo.nombre }} {{ personaInfo.apellido }}</a>
    </div>
    {% endfor %}
{% endblock %}

app3/templates/vistaUsuario.html
{% extends "layout.html" %}

{% block title %}
    {{ objPersona.nombre }} {{ objPersona.apellido }}
{% endblock %}

{% block contenido %}
    <h1>{{ objPersona.nombre }} {{ objPersona.apellido }}</h1>
    <br>
    <div>
        <h4>Numero : {{ objPersona.numero }}</h4>
    </div>
    <div>
        <h4>Email : {{ objPersona.email }}</h4>
    </div>
    <div>
        <h4>Descripcion : {{ objPersona.descripcion }}</h4>
    </div>
    <div>
        <h4>Departamento : {{ objPersona.depaRelacionado.nombreDepartamento }}</h4>
    </div>
{% endblock %}