app1/urls.py
from django.urls import path, include
from . import views

app_name = 'app1'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('nuevaRuta', views.nuevo, name='nuevo'),
    path('welcome', views.welcome, name='welcome'),
]

app4/urls.py
from django.urls import path, include
from . import views

app_name = 'app4'

urlpatterns = [
    path('', views.ingresoUsuario, name='ingresoUsuario'),
    path('informacionUsuario',views.informacionUsuario,name='informacionUsuario'),
    path('cerrarSesion',views.cerrarSesion,name='cerrarSesion'),
    path('ejemploJs',views.ejemploJs,name='ejemploJs'),
    path('crearPublicacion',views.crearPublicacion,name='crearPublicacion'),
    path('devolverDatos',views.devolverDatos,name='devolverDatos'),
    path('devolverUsuario',views.devolverUsuario,name='devolverUsuario'),
    path('devolverPub',views.devolverPub,name='devolverPub'),
    path('eliminarPub/<str:idPub>',views.eliminarPub,name='eliminarPub'),
    path('publicarComentario',views.publicarComentario,name='publicarComentario'),
    path('descargarReporte',views.descargarReporte,name='descargarReporte'),
    path('reactjs',views.reactjs,name='reactjs')
]

miPrimerProyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1',include('app1.urls')),
    path('app2',include('app2.urls')),
    path('app3/',include('app3.urls')),
    path('',include('app4.urls'))
]

#DIRECCION BASE : 127.0.0.1:8000 / app2 /

app4/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class datosUsuario(models.Model):
    profesion = models.CharField(max_length=48, null=True, blank=True)
    nroCelular = models.CharField(max_length=16, null=True, blank=True)
    perfilUsuario = models.CharField(max_length=256, null=True, blank=True)
    usuarioRelacionado = models.OneToOneField(User,null=True,blank=True,on_delete=models.CASCADE)

class publicacion(models.Model):
    titulo = models.CharField(max_length=64, null=True, blank=True)
    descripcion = models.CharField(max_length=256, null=True, blank=True)
    autorPublicacion = models.ForeignKey(User, on_delete=models.CASCADE)

class comentario(models.Model):
    descripcion = models.CharField(max_length=256, null=True, blank=True)
    pubRelacionada = models.ForeignKey(publicacion, on_delete=models.CASCADE)
    autorComentario = models.ForeignKey(User,on_delete=models.CASCADE)

app4/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse, FileResponse
from django.urls import reverse
from .models import datosUsuario, publicacion, comentario
from django.contrib.auth.models import User
import json

from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4

# Create your views here.
def ingresoUsuario(request):
    if request.method == 'POST':
        nombreUsuario = request.POST.get('nombreUsuario')
        contraUsuario = request.POST.get('contraUsuario')
        usrObj = authenticate(request,username=nombreUsuario, password=contraUsuario)
        if usrObj is not None:
            login(request,usrObj)
            return HttpResponseRedirect(reverse('app4:informacionUsuario'))
        else:
            return HttpResponseRedirect(reverse('app4:ingresoUsuario'))
    return render(request,'ingresoUsuario.html')

@login_required(login_url='/')
def informacionUsuario(request):
    allPubs = publicacion.objects.all().order_by('-id')
    return render(request,'informacionUsuario.html',{
        'allPubs':allPubs
    })

@login_required(login_url='/')
def cerrarSesion(request):
    logout(request)
    return HttpResponseRedirect(reverse('app4:ingresoUsuario'))

def ejemploJs(request):
    return render(request,'ejemploJs.html')

def crearPublicacion(request):
    if request.method == 'POST':
        tituloPub = request.POST.get('tituloPub')
        descripcionPub = request.POST.get('descripcionPub')
        publicacion.objects.create(
            titulo=tituloPub,
            descripcion=descripcionPub,
            autorPublicacion=request.user
        )
        return HttpResponseRedirect(reverse('app4:informacionUsuario'))
    
def devolverDatos(request):
    return JsonResponse({
        'nombre':'Alexander',
        'edad':'25',
        'colegio':'AlmiranteMiguelGrau-Marcona'
    })

def devolverUsuario(request):
    idUsuario = request.GET.get('idUsuario')
    objUsr = User.objects.get(id=idUsuario)
    return JsonResponse({
        'nombre':objUsr.first_name,
        'apellido':objUsr.last_name,
        'email':objUsr.email
    })

def devolverPub(request):
    datosComentarios = []
    idPub = request.GET.get('idPub')
    pubObj = publicacion.objects.get(id=idPub)
    comentariosPub = pubObj.comentario_set.all()
    for comentarioInfo in comentariosPub:
        datosComentarios.append([
            str(comentarioInfo.autorComentario.username),
            comentarioInfo.descripcion
        ])
    return JsonResponse({
        'titulo':pubObj.titulo,
        'descripcion':pubObj.descripcion,
        'nombreAutor':pubObj.autorPublicacion.first_name,
        'apellidoAutor':pubObj.autorPublicacion.last_name,
        'datosComentarios':datosComentarios
    })

def eliminarPub(request,idPub):
    pubObj = publicacion.objects.get(id=idPub)
    pubObj.delete()
    return HttpResponseRedirect(reverse('app4:informacionUsuario'))


def publicarComentario(request):
    datosComentario = json.load(request)
    comentarioTexto = datosComentario.get('comentario')
    idPublicacion = datosComentario.get('idPublicacion')
    objPublicacion = publicacion.objects.get(id=idPublicacion)
    comentario.objects.create(
        descripcion=comentarioTexto,
        autorComentario=request.user,
        pubRelacionada=objPublicacion
    )
    return JsonResponse({
        'resp':'ok'
    })

def descargarReporte(request):
    pubsAll = publicacion.objects.all().order_by('id')
    nombreArchivo = 'reporte.pdf'
    reportePub = canvas.Canvas(nombreArchivo,A4)

    reportePub.drawImage('./app4/static/img/logoApp.png',20,700, width=140,height=80)
    reportePub.drawImage('./app4/static/img/logoPUCP.png',430,700, width=140,height=80)

    reportePub.setFont('Helvetica-Bold',25)
    reportePub.drawCentredString(297.5,730,'REPORTE DE PUBS')

    reportePub.setFont('Helvetica-Bold',12)
    reportePub.drawString(40,620,'Username')
    reportePub.drawString(40,605,'Nombre')
    reportePub.drawString(40,590,'Apellido')
    reportePub.drawString(40,575,'Email')

    reportePub.drawString(155,620,':')
    reportePub.drawString(155,605,':')
    reportePub.drawString(155,590,':')
    reportePub.drawString(155,575,':')

    reportePub.setFont('Helvetica',12)
    reportePub.drawString(160,620,f"{request.user.username}")
    reportePub.drawString(160,605,f"{request.user.first_name}")
    reportePub.drawString(160,590,f"{request.user.last_name}")
    reportePub.drawString(160,575,f"{request.user.email}")

    reportePub.setFont('Helvetica-Bold',12)
    reportePub.drawString(300,620,'Profesion')
    reportePub.drawString(300,605,'Nro Celular')

    reportePub.drawString(425,620,':')
    reportePub.drawString(425,605,':')

    reportePub.setFont('Helvetica',12)
    reportePub.drawString(430,620,f"{request.user.datosusuario.profesion}")
    reportePub.drawString(430,605,f"{request.user.datosusuario.nroCelular}")

    lista_x = [40,550]
    lista_y = [500,540]
    reportePub.setStrokeColorRGB(1,0,0)

    for pubInfo in pubsAll:
        reportePub.grid(lista_x,lista_y)
        reportePub.setFont('Helvetica',12)
        reportePub.drawString(lista_x[0] + 20, lista_y[1] - 15, f"{pubInfo.titulo}")
        reportePub.drawString(lista_x[0] + 220, lista_y[1] - 15, f"{pubInfo.autorPublicacion.username}")
        reportePub.drawString(lista_x[0] + 20, lista_y[1] - 35, f"{pubInfo.descripcion}")
        lista_y[0] = lista_y[0] - 60
        lista_y[1] = lista_y[1] - 60
    reportePub.save()

    reportePubFile = open(nombreArchivo,'rb')
    return FileResponse(reportePubFile,as_attachment=True)

def reactjs(request):
    return render(request,'react.html')

app4/templates/consolaAdministrador.html
<!DOCTYPE html>
<html>
    <head>
        <title>Vista de ingreso</title>
        <!--Importar bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <!--Importar fontAwesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    </head>
    <body>
        <div class="bg-primary">
            <div class="container">
                <div class="row justify-content-between align-items-center">
                    <div class="col-4 mt-3 mb-3 text-white">
                        <div class="row">
                            <h5>Bienvenido {{ NOMBRE USUARIO }}</h5>
                        </div>
                        <div class="row">
                            <h5>{{ PROFESION DEL USUARIO }}</h5>
                        </div>
                    </div>
                    <div class="col-1">
                        <a class="btn btn-success" href="#"><i class="fa-solid fa-right-to-bracket"></i> Salir</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container mt-3 mb-3">
            <div>
                <a href="#" class="btn btn-info">Volver <i class="fa-solid fa-arrow-left"></i></a>
            </div>
        </div>
        <div class="mt-5 text-center">
            <h1>Gestion de usuariso</h1>
        </div>
        <div class="mt-5 container">
            <div class="row justify-content-between">
                <div class="col-2">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevoUsuario"><i class="fa-solid fa-user-plus"></i> Agregar usuario</button>
                </div>
                <div class="col-2">
                    <a class="btn btn-success" href="#"><i class="fa-solid fa-download"></i> Descargar</a>
                </div>
            </div>
        </div>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <table class="table table-bordered">
                        <thead class="table-dark">
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Numero de celular</th>
                            <th>Fecha de registro</th>
                            <th>Editar</th>
                            <th>Eliminar</th>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ NOMBRE USUARIO }}</td>
                                <td>{{ APELLIDO USUARIO }}</td>
                                <td>{{ CELULAR USUARIO }}</td>
                                <td>{{ FECHA REGISTRO USUARIO }}</td>
                                <td class="text-center"><a class="btn btn-warning" href="#"><i class="fa-solid fa-edit"></i></a></td>
                                <td class="text-center"><a class="btn btn-danger" href="#"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

<!--Nuevo usuario-->
<div class="modal fade" id="nuevoUsuario" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form method="post" action="#">
                <div class="modal-header">
                    <h5 class="modal-title">Crear nuevo usuario</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Username :</label>
                            <input class="form-control" type="text" name="usernameUsuario" required>
                        </div>
                        <div class="col-5">
                            <label>Password :</label>
                            <input class="form-control" type="password" name="contraUsuario" required>
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Nombre :</label>
                            <input class="form-control" type="text" name="nombreUsuario" required>
                        </div>
                        <div class="col-5">
                            <label>Apellido :</label>
                            <input class="form-control" type="text" name="apellidoUsuario" required>
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Profesion :</label>
                            <input class="form-control" type="text" name="profesionUsuario" required>
                        </div>
                        <div class="col-5">
                            <label>Email :</label>
                            <input class="form-control" type="email" name="emailUsuario" required>
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Tipo de usuario :</label>
                            <select class="form-select" name="tipoUsuario">
                                <option value="USUARIO">Usuario</option>
                                <option value="ADMINISTRADOR">Administrador</option>
                            </select>
                        </div>
                        <div class="col-5">
                            <label>Nro de celular :</label>
                            <input class="form-control" type="text" name="nroCelular" required>
                        </div>
                    </div>
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-11">
                            <label>Perfil del usuario :</label>
                            <textarea class="form-control" type="text" name="perfilUsuario" rows="4" required></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

app4/templates/ejemploJs.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Ejemplo Js</title>
        <script src="{% static 'js/ejemploJs.js' %}"></script>
    </head>
    <body>
        <h1 id="numeroEditar">0</h1>
        <div>
            <button onclick="incrementarNumero()">Incrementar</button>
            <button onclick="decrementarNumero()">Decrementar</button>
        </div>
        <div>
            <select id="valorNumero" onchange="cargarNumero()">
                <option value="a"></option>
                <option value="25">25</option>
                <option value="50">50</option>
                <option value="75">75</option>
                <option value="100">100</option>
                <option value="125">125</option>
            </select>
            <input id="numeroSelect">
            <button onclick="agregarNumero()">Agregar</button>
            <button onclick="actualizarSuma()">SUMAR</button>
        </div>
        <br>
        <h4>Lista de numeros : </h4>
        <div>
            <ul id="listaNumeros">
            </ul>
        </div>
        <div>
            LA SUMA DE LOS ELEMENTOS DE LA LISTA ES <i id="sumaFinal">SUMA</i>
        </div>
    </body>
</html>

app4/templates/informacionUsuario.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Vista de ingreso</title>
        <!--Importar bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <!--Importar fontAwesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

        <!--Importar scripts de javascript-->
        <script src="{% static 'js/informacionUsuario.js' %}"></script>
    </head>
    <body>
        <div class="bg-primary">
            <div class="container">
                <div class="row justify-content-between align-items-center">
                    <div class="col-4 mt-3 mb-3 text-white">
                        <div class="row">
                            <h5>Bienvenido {{ user.first_name }} {{ user.last_name }}</h5>
                        </div>
                        <div class="row">
                            <h5>{{ user.datosusuario.profesion }}</h5>
                        </div>
                    </div>
                    <div class="col-1">
                        <a class="btn btn-success" href="{% url 'app4:cerrarSesion' %}"><i class="fa-solid fa-right-to-bracket"></i> Salir</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container mt-3 mb-3">
            <div>
                <a href="#" class="btn btn-info">Panel de control <i class="fa-solid fa-arrow-right"></i></a>
            </div>
        </div>
        <div class="mt-5 text-center mb-3">
            <h1 id="pruebaJs">Informacion del usuario : {{ user.first_name }} {{ user.last_name }}</h1>
        </div>
        <div class="container">
            <div class="row justify-content-between">
                <div class="col-5 bg-light" style="border-radius: 20px;">
                    <div class="row mb-2 mt-2">
                        <div class="col-5">
                            <h5>Nombre completo : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ user.first_name }} {{ user.last_name }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Nombre de usuario : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ user.username }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Email : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ user.email }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Profesion del usuario : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ user.datosusuario.profesion }}</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Nro de celular : </h5>
                        </div>
                        <div class="col-7">
                            <i>{{ user.datosusuario.nroCelular }}</i>
                        </div>
                    </div>
                    <!--
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Tipo de usuario : </h5>
                        </div>
                        <div class="col-7">
                            <i>TIPO</i>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-5">
                            <h5>Fecha de registro : </h5>
                        </div>
                        <div class="col-7">
                            <i>FECHA</i>
                        </div>
                    </div>
                    -->
                </div>
                <div class="col-5 bg-light h-100" style="border-radius: 20px;">
                    <div class="row mb-2 mt-2">
                        <div class="col-5">
                            <h5>Perfil : </h5>
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-12">
                            <i>{{ user.datosusuario.perfilUsuario }}</i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-5 text-center mb-3">
            <h3>Publicaciones del usuario</h3>
        </div>
        <div class="container mt-5">
            <div class="row justify-content-between">
                <div class="col-2 text-start">
                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#nuevaTarea"><i class="fa-solid fa-calendar-plus"></i> Nuevo Tweet</button>
                </div>
                <div class="col-2 text-end">
                    <a class="btn btn-success" href="{% url 'app4:descargarReporte' %}"><i class="fa-solid fa-download"></i> Descargar</a>
                </div>
            </div>
        </div>
        <div class="mt-5 container">
            <div class="row justify-content-center">
                <div class="col-8">
                    <table class="table table-bordered">
                        <thead class="table-dark">
                            <th>Autor</th>
                            <th>Titulo</th>
                            <th>Ver tweet</th>
                            <th>Eliminar</th>
                        </thead>
                        <tbody>
                            {% for pubInfo in allPubs %}
                            <tr>
                                <td>{{ pubInfo.autorPublicacion.username }}</td>
                                <td>{{ pubInfo.titulo }}</td>
                                <td><button data-bs-toggle="modal" id="{{ pubInfo.id }}" onclick="devolverPub(this.id)" data-bs-target="#detallePub" class="btn btn-info"><i class="fa-solid fa-eye"></i></button></td>
                                <td><a class="btn btn-danger" href="{% url 'app4:eliminarPub' pubInfo.id %}"><i class="fa-solid fa-trash"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>
</html>

<!--Nueva Publicacion Tweet-->
<div class="modal fade" id="nuevaTarea" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <form method="post" action="{% url 'app4:crearPublicacion' %}">
            {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title">Crear nueva publicacion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-12">
                            <label>Titulo</label>
                            <input class="form-control" type="text" name="tituloPub" required>
                        </div>
                        <!--
                        <div class="col-5">
                            <label>Responsable de la tarea</label>
                            <select class="form-select" name="responsableTarea" required></select>
                        </div>-->
                    </div>
                    <!--
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-5">
                            <label>Fecha de inicio</label>
                            <input class="form-control" type="date" required name="fechaInicio">
                        </div>
                        <div class="col-5">
                            <label>Fecha de finalizacion</label>
                            <input class="form-control" type="date" required name="fechaFin">
                        </div>
                    </div>-->
                    <div class="row form-group justify-content-around mb-3">
                        <div class="col-12">
                            <label>Descripcion de la publicacion</label>
                            <textarea class="form-control" type="text" required rows="4" name="descripcionPub"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!--Detalle Tweet-->
<div class="modal fade" id="detallePub" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Detalle de la publicacion</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h1 style="display: none;" id="idPublicacion"></h1>
                <div class="row form-group justify-content-around mb-3">
                    <div class="col-8">
                        <label>Titulo</label>
                        <input class="form-control" type="text" readonly id="tituloPub">
                    </div>
                    <div class="col-4">
                        <label>Autor</label>
                        <input class="form-control" type="text" readonly id="autorPub">
                    </div>
                </div>
                <div class="row form-group justify-content-around mb-3">
                    <div class="col-12">
                        <label>Contenido de la publicacion</label>
                        <textarea class="form-control" type="text" rows="4" readonly id="descripcionPub"></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12" id="comentariosTotales">
                        <div class="row mb-3">
                            <div class="col-3">
                                Nombre Usuario
                            </div>
                            <div class="col-9">
                                Comentario realizado por un usuario
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-3">
                                Nombre Usuario
                            </div>
                            <div class="col-9">
                                Comentario realizado por un usuario
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col-3">
                                Nombre Usuario
                            </div>
                            <div class="col-9">
                                Comentario realizado por un usuario
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row form-group justify-content-center">
                    <div class="col-10">
                        <input class="form-control" type="text" id="comentarioUsuario">
                    </div>
                    <div class="col-2">
                        <button class="btn btn-info" onclick="enviarComentario()">Comentar</button>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>